# Generated by Django 4.0.2 on 2022-02-14 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('secret_word', models.CharField(max_length=200, verbose_name='Секретное слово')),
                ('favorite_colour', models.CharField(max_length=200, verbose_name='Любимый цвет')),
                ('favorite_food', models.CharField(max_length=200, verbose_name='Любимая еда')),
            ],
        ),
    ]
